language: node_js
node_js:
  - "8"

cache: yarn

branches:
  only:
  - develop
  - master
  - /^greenkeeper/.*$/

before_install:
  - yarn global add serverless
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn

before_script:
  - greenkeeper-lockfile-update
  - yarn test:coverage

script:
  - yarn build

after_script:
  - greenkeeper-lockfile-upload

deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: yarn deploy:prod
    on:
      node: "8"
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: yarn deploy:prod
    on:
      node: "8"
      branch: master
