language: node_js
node_js:
  - "8"

cache: yarn

env:
- NODE_ENV: test

branches:
  only:
  - develop
  - master
  - /^greenkeeper/.*$/

before_install:
  - yarn global add serverless greenkeeper-lockfile@1

install:
  - yarn

before_script:
  - greenkeeper-lockfile-update
  - yarn test:coverage

script:
  - yarn build

after_script:
  - greenkeeper-lockfile-upload
