type Movie {
  id: ID!
  title: String!
  tagline: String
  overview: String
  status: ReleaseStatus!
  releaseDate: String!
  runtime: Int
  budget: Int!
  revenue: Int!
  poster: Poster
  backdrop: Backdrop
  popularity: Float!
  score: Float!
  votes: Int!
  genres: [Genre!]!
  languages: [Language!]!
  cast(limit: Int): [Cast!]!
  crew(limit: Int): [Crew!]!
  videos(filter: VideoFilter first: Int): [Video!]!
  similar(limit: Int): [Movie!]!
}
